In [11]:
from TCRdist_gpu import *

In [2]:
tst_tcr = load_TCR_file()
params_df, params_vec = load_params_file()
submat = load_substitution_matrix()
encoded1, tcr1 = encode_TCRs(tst_tcr, params_vec, n_max = 40000)
encoded2, tcr2 = encode_TCRs(tst_tcr, params_vec, n_max = 40000)

In [3]:
scores = TCRdist_batch(tcr1, tcr2, submat = submat, tcrdist_cutoff=90, output = "edge_list", chunk_size=1000, print_chunk_size=10000, print_res = True)

total number of chunks (rows): 40
total number of chunks (cols): 40
Processing chunk (rows) 0
Processing chunk (rows) 10000
Processing chunk (rows) 20000
Processing chunk (rows) 30000
Time taken: 10.172045 seconds


In [9]:
scores[scores.TCRdist == 0]

Empty DataFrame
Columns: [edge1_0index, edge2_0index, TCRdist]
Index: []

In [10]:
scores.to_parquet("../output/TCRdist_output/junk.parquet")

In [2]:
tst_tcr = load_TCR_file()
params_df, params_vec = load_params_file()
submat = load_substitution_matrix()
encoded1, tcr1 = encode_TCRs(tst_tcr, params_vec, n_max = 1000)
encoded2, tcr2 = encode_TCRs(tst_tcr, params_vec, n_max = 1000)
scores_sparse, scores_edge_list = TCRdist_simple(tcr1, tcr2, submat = submat, output = "both")
print(scores_edge_list)
print(scores_sparse)

   row_0index  col_0index  TCRdist
0         143         144       81
1         144         143       81
2         259         267       69
3         262         301       72
4         267         259       69
5         301         262       72
6         572         971       64
7         971         572       64
<Compressed Sparse Row sparse matrix of dtype 'uint8'
	with 8 stored elements and shape (1000, 1000)>
  Coords	Values
  (143, 144)	81
  (144, 143)	81
  (259, 267)	69
  (262, 301)	72
  (267, 259)	69
  (301, 262)	72
  (572, 971)	64
  (971, 572)	64


In [ ]:
### example with edge_list and batching
from TCRdist_gpu import *
tst_tcr = load_TCR_file()
params_df, params_vec = load_params_file()
submat = load_substitution_matrix()
encoded1, tcr1 = encode_TCRs(tst_tcr, params_vec, n_max = np.inf)
encoded2, tcr2 = encode_TCRs(tst_tcr, params_vec, n_max = np.inf)
chunk_n = 1000
res = TCRdist_batch(tcr1, tcr2, submat = submat, tcrdist_cutoff=90, output = "edge_list", chunk_size=chunk_n, print_chunk_size=5000, print_res = True)
#res.to_parquet("../output/TCRdist_output/covid_745k_tcrdist_cutoff_90.parquet")

total number of chunks (rows): 745
total number of chunks (cols): 745
Processing chunk (rows) 0
Processing chunk (rows) 5000
Processing chunk (rows) 10000
Processing chunk (rows) 15000
Processing chunk (rows) 20000
Processing chunk (rows) 25000
Processing chunk (rows) 30000
Processing chunk (rows) 35000
Processing chunk (rows) 40000
Processing chunk (rows) 45000
Processing chunk (rows) 50000
Processing chunk (rows) 55000
Processing chunk (rows) 60000
Processing chunk (rows) 65000
Processing chunk (rows) 70000
Processing chunk (rows) 75000
Processing chunk (rows) 80000
Processing chunk (rows) 85000
Processing chunk (rows) 90000
Processing chunk (rows) 95000
Processing chunk (rows) 100000
Processing chunk (rows) 105000
Processing chunk (rows) 110000
Processing chunk (rows) 115000
Processing chunk (rows) 120000
Processing chunk (rows) 125000
Processing chunk (rows) 130000
Processing chunk (rows) 135000
Processing chunk (rows) 140000
Processing chunk (rows) 145000
Processing chunk (rows) 1

OSError: Cannot save file into a non-existent directory: 'output/TCRdist_output'

In [12]:
res.to_parquet("../output/TCRdist_output/covid_745k_tcrdist_cutoff_90.parquet")

In [ ]:
### note: parquet is smaller than sparse csr matrix, so just write parquet
#coo_mat = scipy.sparse.coo_matrix((res['TCRdist'], (res['row_0index'], res['col_0index'])))
#csr_mat = coo_mat.tocsr()
#scipy.io.mmwrite("covid_745k_tcrdist_cutoff_120.mtx", csr_mat)

In [1]:
### example with covid and vdj inputs
from TCRdist_gpu import *
tcr_both = pd.read_parquet(os.path.join("data", "vdj_and_covid_032425.parquet"))
params_df, params_vec = load_params_file()
submat = load_substitution_matrix()
encoded1, tcr1 = encode_TCRs(tcr_both, params_vec, n_max = np.inf)
encoded2, tcr2 = encode_TCRs(tcr_both, params_vec, n_max = np.inf)

In [1]:
from TCRdist_gpu import *
tcr_both = pd.read_parquet(os.path.join("data", "vdj_and_covid_032425.parquet"))
tcr1 = tcr_both[:20000]
tcr2 = tcr_both[:20000]
params_df, _ = load_params_file()
#submat = np.loadtxt(os.path.join("data", 'TCRdist_matrix_mega.tsv'), delimiter='\t', dtype=np.int16)
submat = load_substitution_matrix()
chunk_n = 1000
res = TCRdist_batch(tcr1, submat = submat, params_df = params_df, tcrdist_cutoff=90,chunk_size=chunk_n, print_chunk_size=chunk_n, print_res = True, only_lower_tri = True)
#chunk_n = 1000
#res = TCRdist_batch(tcr1, tcr2, submat = submat, tcrdist_cutoff=90, output = "edge_list", chunk_size=chunk_n, print_chunk_size=chunk_n, print_res = True)

Checking for available GPU...

Apple Silicon GPU detected:
Apple Silicon GPU (M1/M2/M3)
Checking for GPU-related Python modules...

'mlx' is installed (for Apple Silicon GPUs).
Loading mlx to perform TCRdist
total number of chunks (rows): 20
total number of chunks (cols): 20
Processing chunk (rows) 0
Processing chunk (rows) 1000
Processing chunk (rows) 2000
Processing chunk (rows) 3000
Processing chunk (rows) 4000
Processing chunk (rows) 5000
Processing chunk (rows) 6000
Processing chunk (rows) 7000
Processing chunk (rows) 8000
Processing chunk (rows) 9000
Processing chunk (rows) 10000
Processing chunk (rows) 11000
Processing chunk (rows) 12000
Processing chunk (rows) 13000
Processing chunk (rows) 14000
Processing chunk (rows) 15000
Processing chunk (rows) 16000
Processing chunk (rows) 17000
Processing chunk (rows) 18000
Processing chunk (rows) 19000
Time taken: 1.593779 seconds


In [ ]:
from TCRdist_gpu import *
## load data
tcr_both = pd.read_parquet(os.path.join("data", "vdj_and_covid_032425.parquet"))
params_df, _ = load_params_file()
submat = load_substitution_matrix()

### 2 sets of TCRs
# print(check_batch(tcr1 = tcr_both[:2000], tcr2 = tcr_both[5000:7000], submat = submat, params_df = params_df, tcrdist_cutoff = 90))
# print(check_batch(tcr1 = tcr_both[:579], tcr2 = tcr_both[5000:10001], submat = submat, params_df = params_df, tcrdist_cutoff = 90))

### set of TCRs against themselves
# print(check_batch(tcr1 = tcr_both[:2000], submat = submat, params_df = params_df, tcrdist_cutoff = 90))
# print(check_batch(tcr1 = tcr_both[:781], submat = submat, params_df = params_df, tcrdist_cutoff = 120))
# print(check_batch(tcr1 = tcr_both[:1000], submat = submat, params_df = params_df, tcrdist_cutoff = np.inf))

# print(check_batch(tcr1 = tcr_both[:3021], submat = submat, params_df = params_df, tcrdist_cutoff = np.inf))
# print(check_batch(tcr1 = tcr_both[:5000], submat = submat, params_df = params_df, tcrdist_cutoff = 120))
# print(check_batch(tcr1 = tcr_both[:4001], submat = submat, params_df = params_df, tcrdist_cutoff = 90))



array([[0, 287, 251, ..., 318, 354, 327],
       [287, 0, 275, ..., 323, 409, 271],
       [251, 275, 0, ..., 281, 356, 235],
       ...,
       [318, 323, 281, ..., 0, 360, 297],
       [354, 409, 356, ..., 360, 0, 311],
       [327, 271, 235, ..., 297, 311, 0]], dtype=int32)
Time taken: 0.000020 seconds
total number of chunks (rows): 3
total number of chunks (cols): 3
Processing chunk (rows) 0
Processing chunk (rows) 1000
Processing chunk (rows) 2000
Processing chunk (rows) 3000
Time taken: 0.141346 seconds
True
array([[0, 287, 251, ..., 319, 289, 324],
       [287, 0, 275, ..., 291, 215, 313],
       [251, 275, 0, ..., 235, 267, 274],
       ...,
       [319, 291, 235, ..., 0, 261, 302],
       [289, 215, 267, ..., 261, 0, 248],
       [324, 313, 274, ..., 302, 248, 0]], dtype=int32)
Time taken: 0.000020 seconds
total number of chunks (rows): 5
total number of chunks (cols): 5
Processing chunk (rows) 0
Processing chunk (rows) 1000
Processing chunk (rows) 2000
Processing chunk (rows)

In [7]:
df1.to_parquet('df1.parquet')
df2.to_parquet('df2.parquet')

In [ ]:
df1['TCRdist'].tolist() == df2['TCRdist'].tolist()
df1['edge1_0index'].tolist() == df2['edge1_0index'].tolist()
df1['edge2_0index'].tolist() == df2['edge2_0index'].tolist()


False

In [2]:
from pandas.testing import assert_frame_equal

try:
    assert_frame_equal(df1, df2)
except AssertionError as e:
    print(e)

DataFrame.index are different

DataFrame.index values are different (74.76243 %)
[left]:  RangeIndex(start=0, stop=1999000, step=1)
[right]: Index([      0,       1,       2,       3,       4,       5,       6,       7,
             8,       9,
       ...
       1998990, 1998991, 1998992, 1998993, 1998994, 1998995, 1998996, 1998997,
       1998998, 1998999],
      dtype='int64', length=1999000)
At positional index 501500, first diff: 501500 != 1499500


In [3]:
print(res['TCRdist_df'])
res['tcr1']

       edge1_0index  edge2_0index  TCRdist
0                 2            23       81
1                 2           876       81
2                 3            17       33
3                 3            18       33
4                 3            39       33
...             ...           ...      ...
40205         19969         19992        0
40206         19971         19973       54
40207         19972         19991       33
40208         19981         19996       72
40209         19990         19991       90

[40210 rows x 3 columns]


va           vb              cdr3a            cdr3b  \
0             TRAV3*01   TRBV5-1*01    CAVRDGGTGFQKLVF  CASRQDRDYQETQYF   
1          TRAV13-1*01     TRBV9*01    CAARGIGSGTYKYIF     CASSARSGELFF   
2             TRAV3*01    TRBV19*01      CAVRDGTANNLFF    CASSISSTGELFF   
3          TRAV38-1*01    TRBV19*01  CAFMKDAGGTSYGKLTF     CASSIGVYGYTF   
4            TRAV27*01    TRBV19*01       CAGGGSQGNLIF    CASSIRSSYEQYF   
...                ...          ...                ...              ...   
19995       TRAV1-2*01  TRBV20-1*01     CAVRALNRDDKIIF     CSARGRRDKAFF   
19996      TRAV26-1*01    TRBV19*01      CIVRETGANNLFF   CASSIFSAYNEQFF   
19997        TRAV10*01  TRBV12-4*01     CVVSLDTGRRALTF   CASSFGTSSDTQYF   
19998  TRAV38-2/DV8*01    TRBV19*01    CAYRSARGGSEKLVF  CASSILAGGYNEQFF   
19999    TRAV29/DV5*01   TRBV4-3*01    CAASAANQAGTALIF   CASSPGQGWNGYTF   

        clone_name  clone_idx_1index  clone_idx_0index  
0          vdjdb 1                 1               0.0  
1          vdjdb 2                 2               1.0  
2          vdjdb 3                 3               2.0  
3          vdjdb 4                 4               3.0  
4          vdjdb 5                 5               4.0  
...            ...               ...               ...  
19995  vdjdb 19996             19996           19995.0  
19996  vdjdb 19997             19997           19996.0  
19997  vdjdb 19998             19998           19997.0  
19998  vdjdb 19999             19999           19998.0  
19999  vdjdb 20000             20000           19999.0  

[20000 rows x 7 columns]

In [3]:
res

edge1_0index  edge2_0index  TCRdist
0                  2            23       81
1                  2           876       81
2                  3            17       33
3                  3            18       33
4                  3            39       33
...              ...           ...      ...
102871         38187         39360       33
102872         38729         39122       90
102873         38921         39564       48
102874         39180         39182       84
102875         39434         39933       54

[102876 rows x 3 columns]

In [4]:
res.query('TCRdist == 0')

edge1_0index  edge2_0index  TCRdist
17                 4            28        0
46                 7           858        0
340              391           404        0
10343           1148          1670        0
10356           1161          1714        0
10524           1332          1869        0
34621           4273          4324        0
34648           4273          4728        0
34904           4324          4728        0
35850           4699          4764        0
55809           5224          5301        0
68334          18975         18976        0
70463          19028         19029        0
72506          19969         19992        0
83882          20051         20501        0
87402          20686         20950        0
94089          21061         21184        0
94534          21155         21320        0
94665          21249         21250        0
94743          21383         21405        0
94821          21406         21412        0
94843          21407         21420        0
100520         22912         22985        0
102606         28248         28254        0
102609         28734         28779        0
102646         29044         29045        0
102673         30324         30331        0
102736         32039         32050        0

In [5]:
tcr1

va           vb              cdr3a             cdr3b  \
0             TRAV3*01   TRBV5-1*01    CAVRDGGTGFQKLVF   CASRQDRDYQETQYF   
1          TRAV13-1*01     TRBV9*01    CAARGIGSGTYKYIF      CASSARSGELFF   
2             TRAV3*01    TRBV19*01      CAVRDGTANNLFF     CASSISSTGELFF   
3          TRAV38-1*01    TRBV19*01  CAFMKDAGGTSYGKLTF      CASSIGVYGYTF   
4            TRAV27*01    TRBV19*01       CAGGGSQGNLIF     CASSIRSSYEQYF   
...                ...          ...                ...               ...   
39995       TRAV9-2*01   TRBV5-1*01        CALSINYQLIW  CASSLVDSSYNSPLHF   
39996    TRAV23/DV6*01   TRBV5-4*01    CAASPFSGGYNKLIF     CASRPGVGDLQYF   
39997       TRAV9-2*01  TRBV10-3*01         CALRWGKSTF     CAISGASYNEQFF   
39998  TRAV38-2/DV8*01   TRBV5-1*01    CAYRSLVGFGNVLHC    CASTVLAGGNTIYF   
39999         TRAV4*01   TRBV7-3*01       CLVEGSQGNLIF     CASSLTGKNEQFF   

        clone_name  clone_idx_1index  clone_idx_0index  
0          vdjdb 1                 1               0.0  
1          vdjdb 2                 2               1.0  
2          vdjdb 3                 3               2.0  
3          vdjdb 4                 4               3.0  
4          vdjdb 5                 5               4.0  
...            ...               ...               ...  
39995  covid 13783             39996           39995.0  
39996  covid 13784             39997           39996.0  
39997  covid 13785             39998           39997.0  
39998  covid 13786             39999           39998.0  
39999  covid 13787             40000           39999.0  

[40000 rows x 7 columns]

In [10]:
res_old = res.copy()

In [2]:
params_vec = dict(zip(params_df["feature"], params_df["value"]))
tcr1_enc = process_TCRs(tcr1, params_vec=params_vec)
tcr2_enc = process_TCRs(tcr2, params_vec=params_vec)

In [ ]:
tmp = tcr1_enc[slice(0, 1000)]
tmp.shape
names1 = tcr1.clone_name[0:1000]
names1

0         vdjdb 1
1         vdjdb 2
2         vdjdb 3
3         vdjdb 4
4         vdjdb 5
          ...    
995     vdjdb 996
996     vdjdb 997
997     vdjdb 998
998     vdjdb 999
999    vdjdb 1000
Name: clone_name, Length: 1000, dtype: object

In [54]:
arr = mx.array([
    [0, 0, 3],
    [0, 0, 0],
    [3, 0, 0]
])
arr
mask = (arr == 0) & (~np.eye(arr.shape[0], dtype=bool))
mask = mask*(-1)
mask

array([[0, -1, 0],
       [-1, 0, -1],
       [0, -1, 0]], dtype=int32)

In [36]:
mx.less_equal(mx.eye(5,5), 0.5)

array([[False, True, True, True, True],
       [True, False, True, True, True],
       [True, True, False, True, True],
       [True, True, True, False, True],
       [True, True, True, True, False]], dtype=bool)

In [8]:
tcr1

va           vb              cdr3a             cdr3b  \
0             TRAV3*01   TRBV5-1*01    CAVRDGGTGFQKLVF   CASRQDRDYQETQYF   
1          TRAV13-1*01     TRBV9*01    CAARGIGSGTYKYIF      CASSARSGELFF   
2             TRAV3*01    TRBV19*01      CAVRDGTANNLFF     CASSISSTGELFF   
3          TRAV38-1*01    TRBV19*01  CAFMKDAGGTSYGKLTF      CASSIGVYGYTF   
4            TRAV27*01    TRBV19*01       CAGGGSQGNLIF     CASSIRSSYEQYF   
...                ...          ...                ...               ...   
39995       TRAV9-2*01   TRBV5-1*01        CALSINYQLIW  CASSLVDSSYNSPLHF   
39996    TRAV23/DV6*01   TRBV5-4*01    CAASPFSGGYNKLIF     CASRPGVGDLQYF   
39997       TRAV9-2*01  TRBV10-3*01         CALRWGKSTF     CAISGASYNEQFF   
39998  TRAV38-2/DV8*01   TRBV5-1*01    CAYRSLVGFGNVLHC    CASTVLAGGNTIYF   
39999         TRAV4*01   TRBV7-3*01       CLVEGSQGNLIF     CASSLTGKNEQFF   

        clone_name  clone_idx_1index  clone_idx_0index  
0          vdjdb 1                 1               0.0  
1          vdjdb 2                 2               1.0  
2          vdjdb 3                 3               2.0  
3          vdjdb 4                 4               3.0  
4          vdjdb 5                 5               4.0  
...            ...               ...               ...  
39995  covid 13783             39996           39995.0  
39996  covid 13784             39997           39996.0  
39997  covid 13785             39998           39997.0  
39998  covid 13786             39999           39998.0  
39999  covid 13787             40000           39999.0  

[40000 rows x 7 columns]

In [10]:
tcr1[0:3]

va          vb            cdr3a            cdr3b clone_name  \
0     TRAV3*01  TRBV5-1*01  CAVRDGGTGFQKLVF  CASRQDRDYQETQYF    vdjdb 1   
1  TRAV13-1*01    TRBV9*01  CAARGIGSGTYKYIF     CASSARSGELFF    vdjdb 2   
2     TRAV3*01   TRBV19*01    CAVRDGTANNLFF    CASSISSTGELFF    vdjdb 3   

   clone_idx_1index  clone_idx_0index  
0                 1               0.0  
1                 2               1.0  
2                 3               2.0

In [2]:
res

index  edge1_0index  edge2_0index  TCRdist
0          0             1            22       81
1          1             1           875       81
2          2             2            16       33
3          3             2            17       33
4          4             2            38       33
...      ...           ...           ...      ...
40191   4497         19967         19991       81
40192   4574         19970         19972       54
40193   4597         19971         19990       33
40194   4639         19980         19995       72
40195   4705         19989         19990       90

[40196 rows x 4 columns]

In [3]:
res.to_parquet("../output/TCRdist_output/covid_to_vdjdb_tcrdist_cutoff_90.parquet")